apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hello
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: hello
    spec:
      containers:
      - env:
        - name: FLASK_ENV
          value: development
        - name: LOGLEVEL
          value: INFO
        - name: PYTHONUNBUFFERED
          value: "1"
        image: hello:dev
        imagePullPolicy: ""
        name: hello
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
